import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import { InputMessage } from "@/components/input-message";
import { ChatUserHeader } from "@/components/chat-user-header";
import { Sidebar } from "@/components/sidebar";

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)] flex h-screen w-full overflow-hidden`}
			>
				<Sidebar />
				{children}
			</body>
		</html>
	);
}
